# Generated by Django 3.2.6 on 2022-07-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blugz', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
